name: Matt Richard
favicon: null
layout_spectrum: 0.7068
typography_spectrum: 0.42475
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c69172'
    - '#796974'
    - '#65bfd7'
    - '#b6e5eb'
    - '#413299'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
