name: Matt Richard
favicon: null
layout_spectrum: 0.6306280212011188
typography_spectrum: 0.24783760751597583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8328419809695333
  lightness: 0.5537943318486214
  saturation: 0.586302709300071
  rhythmicContrast: 0.40329734701663256
purpose: []
