name: Matt Richard
favicon: null
layout_spectrum: 0.6306280212011188
typography_spectrum: 0.2478376075159758
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070508'
    - '#feffff'
    - '#ff8dae'
    - '#957197'
    - '#f336ea'
  brandStrength: 0.3125
  lightness: 0.3064516
  saturation: 0.2580645
  rhythmicContrast: 0.4032973
purpose: []
